[centos_vms]
centos1 ansible_host=192.168.56.105 ansible_user=zerojay ansible_ssh_private_key_file=/home/zerojay/.ssh/id_ed25519

[ubuntu_vms]
ubuntu1 ansible_host=192.168.56.101 ansible_user=zerojay ansible_ssh_private_key_file=/home/zerojay/.ssh/id_ed25519
ubuntu2 ansible_host=192.168.56.102 ansible_user=zerojay ansible_ssh_private_key_file=/home/zerojay/.ssh/id_ed25519

[all_vms:children]
centos_vms
ubuntu_vms

[all_vms:vars]
ansible_become=yes
ansible_become_method=sudo
